import { store } from "./storage.js?v=1.1.0";
import { initFileTest } from "./file-test.js?v=1.1.0";
import { APP_VERSION, initVersionInfo } from "./version.js?v=1.1.0";

const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const keys = { plans:"plans", people:"people", activities:"activities", circles:"circles", agenda:"agenda", events:"events", bundles:"bundles", places:"places" };
const viewNames = { today:"Today", people:"People", calendar:"Calendar", activities:"Activities", settings:"Settings", changelog:"What’s new" };
const activityIcons = { Fika:"☕", Mat:"🍽", Utomhus:"🌿", Kultur:"🎭", Träning:"⚡", Annat:"✦" };
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const dateKey = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const todayKey = dateKey(new Date());
const read = (key, fallback=[]) => store.get(key, fallback);
const write = (key, value) => store.set(key, value);
const prettyDate = (key, options={weekday:"long",day:"numeric",month:"long"}) => { const [y,m,d]=key.split("-").map(Number); return new Intl.DateTimeFormat("sv-SE",options).format(new Date(y,m-1,d)); };
const initials = (name) => name.split(/\s+/).slice(0,2).map(w=>w[0]).join("").toUpperCase();
const interestList = (value) => Array.isArray(value) ? value : typeof value === "string" ? value.split(",").map(item=>item.trim()).filter(Boolean) : [];

let shownMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
let selectedDate = todayKey, peopleFilter = "Alla", relationshipMode = "people";
let activityFilter = "all", activityCategory = "all", activitySort = "newest", activityContentMode = "activities", calendarMode = "month";
let calendarAgendaMode = "day";
let currentEntity = null;

function namesFor(ids, collection, labelKey="name") {
  return ids.map(id=>collection.find(item=>item.id===id)?.[labelKey]).filter(Boolean);
}

function expandCircleMembers(personIds, circleIds) {
  const circles=read(keys.circles);
  return [...new Set([...personIds, ...circleIds.flatMap(id=>circles.find(c=>c.id===id)?.personIds||[])])];
}

function checkboxList(target, items, name, selected=[]) {
  target.replaceChildren();
  if (!items.length) { const p=document.createElement("p"); p.className="field-empty"; p.textContent="Inga att välja ännu"; target.append(p); return; }
  items.forEach(item=>{const label=document.createElement("label");label.className="check-option";const input=document.createElement("input");input.type="checkbox";input.name=name;input.value=item.id;input.checked=selected.includes(item.id);const span=document.createElement("span");span.textContent=item.name||item.title;label.append(input,span);target.append(label);});
}

function fillActivitySelect(select, selected="") {
  const first=select.querySelector("option[value='']"); select.replaceChildren(first||new Option("Ingen vald aktivitet",""));
  read(keys.activities).forEach(activity=>select.add(new Option(activity.title,activity.id)));
  select.value=selected||"";
}

function showView() {
  const wanted=location.hash.slice(1), active=viewNames[wanted]?wanted:"today";
  $$('[data-view]').forEach(v=>v.classList.toggle("is-active",v.dataset.view===active));
  $$('[data-nav]').forEach(item=>{const on=item.dataset.nav===active;item.classList.toggle("is-active",on);on?item.setAttribute("aria-current","page"):item.removeAttribute("aria-current");});
  $(".bottom-nav").hidden = active === "settings" || active === "changelog";
  $("#open-settings").hidden = active === "settings" || active === "changelog";
  document.title=`${viewNames[active]} · Social Circle`;
}

function completePlan(plan) {
  const plans=read(keys.plans), index=plans.findIndex(p=>p.id===plan.id); if(index<0)return;
  plans[index]={...plans[index],status:"completed",completedAt:new Date().toISOString()};
  const events=read(keys.events);
  if(!events.some(event=>event.sourcePlanId===plan.id)) events.push({id:uid(),sourcePlanId:plan.id,title:plan.title,date:plan.date,time:plan.time||"",activityId:plan.activityId||"",bundleId:plan.bundleId||"",personIds:expandCircleMembers(plan.personIds||[],plan.circleIds||[]),circleIds:plan.circleIds||[],notes:plan.notes||"",createdAt:new Date().toISOString()});
  store.set(keys.events,events); store.set(keys.plans,plans);
}

function makePlanCard(plan, allPlans, target) {
  const card=document.createElement("article");card.className=`plan-card clickable-card${plan.status==="completed"?" is-completed":""}`;card.tabIndex=0;card.setAttribute("role","button");card.onclick=()=>openPlanDialog("",plan);card.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openPlanDialog("",plan);}};
  const time=document.createElement("span");time.className="plan-time";time.textContent=plan.time;
  const details=document.createElement("div"),title=document.createElement("h3"),sub=document.createElement("p");title.textContent=plan.title;
  const people=namesFor(plan.personIds||[],read(keys.people)); const circles=namesFor(plan.circleIds||[],read(keys.circles)); sub.textContent=[plan.date===todayKey?"Idag":prettyDate(plan.date,{day:"numeric",month:"short"}),...people,...circles].join(" · ");details.append(title,sub);
  const actions=document.createElement("div");actions.className="plan-actions";
  if(plan.status!=="completed"){const done=document.createElement("button");done.type="button";done.className="complete-button";done.textContent="✓";done.title="Markera som genomförd";done.onclick=e=>{e.stopPropagation();completePlan(plan);};actions.append(done);}
  const remove=document.createElement("button");remove.type="button";remove.textContent="×";remove.setAttribute("aria-label",`Ta bort ${plan.title}`);remove.onclick=e=>{e.stopPropagation();write(keys.plans,allPlans.filter(i=>i.id!==plan.id));};actions.append(remove);card.append(time,details,actions);target.append(card);
}

function makeEventCard(event, target) {
  const card=document.createElement("article");card.className="history-card";
  const activity=read(keys.activities).find(a=>a.id===event.activityId);const people=namesFor(event.personIds||[],read(keys.people));const circles=namesFor(event.circleIds||[],read(keys.circles));
  const date=document.createElement("time");date.textContent=`${prettyDate(event.date,{day:"numeric",month:"short"})}${event.time?` · ${event.time}`:""}`;
  const title=document.createElement("h3");title.textContent=event.title;
  const meta=document.createElement("p");meta.textContent=[activity?.title,...people,...circles].filter(Boolean).join(" · ")||"Social händelse";
  card.append(date,title,meta);if(event.notes){const notes=document.createElement("p");notes.className="history-notes";notes.textContent=event.notes;card.append(notes);}target.append(card);
}

function renderToday() {
  const all=read(keys.plans).map(p=>({...p,date:p.date||todayKey,status:p.status||"planned"})),plans=all.filter(p=>p.date===todayKey).sort((a,b)=>a.time.localeCompare(b.time));
  $("#plan-list").replaceChildren();$("#empty-state").hidden=plans.length>0;$("#plan-count").textContent=`${plans.length} ${plans.length===1?"plan":"planer"}`;plans.forEach(p=>makePlanCard(p,all,$("#plan-list")));
}

function renderPeople() {
  const people=read(keys.people),visible=peopleFilter==="Alla"?people:people.filter(p=>p.group===peopleFilter);$("#people-list").replaceChildren();$("#people-empty").hidden=visible.length>0;
  visible.forEach(person=>{const card=document.createElement("article");card.className="person-card clickable-card";card.tabIndex=0;card.setAttribute("role","button");card.onclick=()=>openEntity("person",person.id);card.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")openEntity("person",person.id);};const avatar=document.createElement("span");avatar.className="person-avatar";avatar.textContent=initials(person.name);const info=document.createElement("div"),name=document.createElement("h2"),meta=document.createElement("p");name.textContent=person.name;const agendaCount=read(keys.agenda).filter(a=>a.ownerType==="person"&&a.ownerId===person.id&&!a.completedAt).length,interestText=interestList(person.interests).slice(0,2).join(", ");meta.textContent=[person.group,interestText,`${agendaCount} på agendan`].filter(Boolean).join(" · ");info.append(name,meta);const arrow=document.createElement("span");arrow.className="card-arrow";arrow.textContent="›";card.append(avatar,info,arrow);$("#people-list").append(card);});
  renderCircles();
}

function renderCircles() {
  const circles=read(keys.circles),people=read(keys.people);$("#circles-list").replaceChildren();$("#circles-empty").hidden=circles.length>0;
  circles.forEach(circle=>{const card=document.createElement("article");card.className="person-card circle-card clickable-card";card.tabIndex=0;card.setAttribute("role","button");card.onclick=()=>openEntity("circle",circle.id);const avatar=document.createElement("span");avatar.className="person-avatar circle-avatar";avatar.textContent="◯";const info=document.createElement("div"),name=document.createElement("h2"),meta=document.createElement("p");name.textContent=circle.name;const members=namesFor(circle.personIds||[],people);meta.textContent=members.length?members.join(", "):"Inga personer ännu";info.append(name,meta);const arrow=document.createElement("span");arrow.className="card-arrow";arrow.textContent="›";card.append(avatar,info,arrow);$("#circles-list").append(card);});
}

const addDays=(date,days)=>new Date(date.getFullYear(),date.getMonth(),date.getDate()+days);
const mondayOf=(date)=>addDays(date,-((date.getDay()+6)%7));
function renderCalendar() {
  const plans=read(keys.plans).map(p=>({...p,date:p.date||todayKey})),events=read(keys.events),grid=$("#calendar-grid"),weekdays=$(".calendar-weekdays");grid.replaceChildren();grid.className="calendar-grid";
  if(calendarMode==="month"){
    const y=shownMonth.getFullYear(),m=shownMonth.getMonth();$("#month-label").textContent=new Intl.DateTimeFormat("sv-SE",{month:"long",year:"numeric"}).format(shownMonth);weekdays.hidden=false;
    const offset=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate();for(let i=0;i<offset;i++){const blank=document.createElement("span");blank.className="calendar-blank";grid.append(blank);}for(let day=1;day<=total;day++)makeCalendarDay(new Date(y,m,day),grid,plans,events,false);
  } else {
    const count=Number(calendarMode),start=count===3?new Date(shownMonth):mondayOf(shownMonth),end=addDays(start,count-1);weekdays.hidden=true;grid.classList.add("range-calendar",`range-${count}`);$("#month-label").textContent=`${prettyDate(dateKey(start),{day:"numeric",month:"short"})} – ${prettyDate(dateKey(end),{day:"numeric",month:"short"})}`;for(let i=0;i<count;i++)makeCalendarDay(addDays(start,i),grid,plans,events,true);
  }
  renderCalendarAgenda(plans,events);renderWeekBalance(plans,events);
}
function renderCalendarAgenda(plans,events){const selected=keyToDate(selectedDate),start=calendarAgendaMode==="week"?mondayOf(selected):selected,end=calendarAgendaMode==="week"?addDays(start,6):start,startKey=dateKey(start),endKey=dateKey(end),inRange=item=>item.date>=startKey&&item.date<=endKey,selectedPlans=plans.filter(inRange).sort((a,b)=>`${a.date} ${a.time||""}`.localeCompare(`${b.date} ${b.time||""}`)),selectedEvents=events.filter(e=>inRange(e)&&(!e.sourcePlanId||!plans.some(p=>p.id===e.sourcePlanId))).sort((a,b)=>`${a.date} ${a.time||""}`.localeCompare(`${b.date} ${b.time||""}`));const label=calendarAgendaMode==="week"?`${prettyDate(startKey,{day:"numeric",month:"short"})} – ${prettyDate(endKey,{day:"numeric",month:"short"})}`:selectedDate===todayKey?"Idag":prettyDate(selectedDate);$("#selected-date-label").textContent=label;$("#calendar-agenda-summary").textContent=calendarAgendaMode==="week"?`Veckan för ${prettyDate(selectedDate,{day:"numeric",month:"short"})}`:label;$("#calendar-plans").replaceChildren();$("#calendar-empty").hidden=selectedPlans.length+selectedEvents.length>0;selectedPlans.forEach(p=>makePlanCard(p,plans,$("#calendar-plans")));selectedEvents.forEach(e=>makeEventCard(e,$("#calendar-plans")));}
function keyToDate(key){const [year,month,day]=key.split("-").map(Number);return new Date(year,month-1,day);}
function scoreForBooking(item,kind){const activities=read(keys.activities),bundle=read(keys.bundles).find(entry=>entry.id===item.bundleId),ids=bundle?.activityIds?.length?bundle.activityIds:item.activityId?[item.activityId]:[],values=ids.map(id=>activities.find(activity=>activity.id===id)?.[kind]).filter(value=>Number.isFinite(Number(value))).map(Number);if(values.length)return values.reduce((sum,value)=>sum+value,0)/values.length;if(kind==="socialLevel"&&((item.personIds||[]).length||(item.circleIds||[]).length))return 2;return null;}
function renderWeekBalance(plans,events){const start=mondayOf(keyToDate(selectedDate)),end=addDays(start,6),startKey=dateKey(start),endKey=dateKey(end),inWeek=item=>item.date>=startKey&&item.date<=endKey;let items,period;if(endKey<todayKey){items=events.filter(inWeek);period="Genomfört";}else if(startKey>todayKey){items=plans.filter(item=>inWeek(item)&&item.status!=="completed");period="Planerat";}else{const completedPlanIds=new Set(events.map(event=>event.sourcePlanId).filter(Boolean));items=[...events.filter(inWeek),...plans.filter(item=>inWeek(item)&&item.status!=="completed"&&!completedPlanIds.has(item.id))];period="Den här veckan";}const weeklyLoad=kind=>{const values=items.map(item=>scoreForBooking(item,kind)).filter(value=>value!==null);return values.length?Math.min(3,values.reduce((sum,value)=>sum+value,0)/2):null;},social=weeklyLoad("socialLevel"),activity=weeklyLoad("activityLevel"),labels={socialLevel:["Mest egen tid","Lite social","Social","Mycket social"],activityLevel:["Mycket lugn","Lugn","Måttlig","Aktiv"]},setMetric=(score,labelId,barId,kind)=>{const rounded=score===null?null:Math.min(3,Math.max(0,Math.round(score)));$(labelId).textContent=rounded===null?"Ingen data":labels[kind][rounded];$(barId).style.width=score===null?"0%":`${Math.max(7,(score/3)*100)}%`;};$("#week-balance-period").textContent=`${period} · ${prettyDate(startKey,{day:"numeric",month:"short"})}–${prettyDate(endKey,{day:"numeric",month:"short"})}`;$("#week-booking-count").textContent=`${items.length} ${items.length===1?"bokning":"bokningar"}`;setMetric(social,"#social-score-label","#social-score-bar","socialLevel");setMetric(activity,"#activity-score-label","#activity-score-bar","activityLevel");let advice="Lägg till aktiviteter med nivåer för att se veckans balans.";if(items.length&&(social!==null||activity!==null)){const tips=[];if(activity!==null&&activity<1)tips.push("Veckan är lugn – det kan finnas plats för något mer aktivt");else if(activity!==null&&activity>2.3)tips.push("Veckan är aktiv – lämna gärna utrymme för återhämtning");if(social!==null&&social<1)tips.push("Du har mycket egen tid och kan överväga något socialt");else if(social!==null&&social>2.3)tips.push("Du har en social vecka – skydda också lite egen tid");advice=tips.join(". ")||"Veckan ser balanserad ut utifrån dina bokningar.";}$("#week-balance-advice").textContent=advice;}
function makeCalendarDay(date,grid,plans,events,range){const key=dateKey(date),items=[...plans.filter(p=>p.date===key),...events.filter(e=>e.date===key&&!e.sourcePlanId)],button=document.createElement("button");button.type="button";button.className=range?"range-day":"calendar-day";if(key===todayKey)button.classList.add("is-today");if(key===selectedDate)button.classList.add("is-selected");if(items.length)button.classList.add("has-plan");if(range){const weekday=document.createElement("small"),number=document.createElement("strong"),list=document.createElement("span");weekday.textContent=new Intl.DateTimeFormat("sv-SE",{weekday:"short"}).format(date);number.textContent=date.getDate();items.slice(0,2).forEach(item=>{const line=document.createElement("i");line.textContent=`${item.time||""} ${item.title}`.trim();list.append(line);});if(items.length>2){const more=document.createElement("i");more.textContent=`+${items.length-2} till`;list.append(more);}button.append(weekday,number,list);}else button.textContent=date.getDate();button.setAttribute("aria-label",prettyDate(key));button.onclick=()=>{selectedDate=key;renderCalendar();};grid.append(button);}
function shiftCalendar(direction){if(calendarMode==="month")shownMonth=new Date(shownMonth.getFullYear(),shownMonth.getMonth()+direction,1);else shownMonth=addDays(shownMonth,direction*Number(calendarMode));selectedDate=dateKey(shownMonth);renderCalendar();}

function renderActivities() {
  let activities=read(keys.activities);activities=activities.map(a=>({...a,cost:Number(a.cost??0),duration:Number(a.duration??60),place:a.place||"Ej angivet"}));let visible=activities.filter(a=>(activityFilter!=="favorite"||a.favorite)&&(activityCategory==="all"||a.category===activityCategory));const sorters={newest:(a,b)=>activities.indexOf(b)-activities.indexOf(a),title:(a,b)=>a.title.localeCompare(b.title,"sv"),cost:(a,b)=>a.cost-b.cost,duration:(a,b)=>a.duration-b.duration,place:(a,b)=>a.place.localeCompare(b.place,"sv")};visible=visible.slice().sort(sorters[activitySort]);$("#activity-grid").replaceChildren();
  visible.forEach(activity=>{const card=document.createElement("article");card.className="activity-card";const top=document.createElement("div");top.className="activity-top";const icon=document.createElement("span");icon.textContent=activityIcons[activity.category]||"✦";const favorite=document.createElement("button");favorite.className=`favorite-button${activity.favorite?" is-favorite":""}`;favorite.textContent=activity.favorite?"♥":"♡";favorite.onclick=()=>{activity.favorite=!activity.favorite;write(keys.activities,activities);};top.append(icon,favorite);const title=document.createElement("h2");title.textContent=activity.title;const meta=document.createElement("p");meta.className="activity-meta";const costs=["Gratis","Billigt","Mellan","Dyrare"],activityLevels=["Mycket lugn","Lugn","Måttlig","Ansträngande"],socialLevels=["Ensam","Lite social","Social","Mycket social"];meta.textContent=`${activity.category} · ${costs[activity.cost]} · ${activity.duration<60?activity.duration+" min":activity.duration/60+" tim"} · ${activity.place}`;const traits=document.createElement("p");traits.className="activity-traits";traits.textContent=activity.activityLevel==null&&activity.socialLevel==null?"Nivåer ej bedömda":[activity.activityLevel==null?null:activityLevels[Number(activity.activityLevel)],activity.socialLevel==null?null:socialLevels[Number(activity.socialLevel)]].filter(Boolean).join(" · ");const actions=document.createElement("div");actions.className="activity-actions";const plan=document.createElement("button");plan.className="small-button";plan.textContent="Planera";plan.onclick=()=>openPlanDialog(activity.title,null,activity.id);const history=document.createElement("button");history.className="text-button";history.textContent="Historik";history.onclick=()=>openEntity("activity",activity.id);const edit=document.createElement("button");edit.className="text-button";edit.textContent="Redigera";edit.onclick=()=>openActivityDialog(activity);actions.append(plan,history,edit);card.append(top,title,meta,traits,actions);$("#activity-grid").append(card);});
  if(!visible.length){const empty=document.createElement("div");empty.className="mini-empty activity-empty";empty.innerHTML="<span>♡</span><h2>Inga träffar</h2><p>Prova ett annat filter.</p>";$("#activity-grid").append(empty);}
}

function renderBundles() {
  const bundles=read(keys.bundles),activities=read(keys.activities),places=read(keys.places);$("#bundle-list").replaceChildren();$("#bundle-empty").hidden=bundles.length>0;
  bundles.forEach(bundle=>{const card=document.createElement("article");card.className="collection-card";const icon=document.createElement("span");icon.className="collection-icon";icon.textContent="✦";const body=document.createElement("div"),title=document.createElement("h2"),meta=document.createElement("p");title.textContent=bundle.name;const activityNames=namesFor(bundle.activityIds||[],activities,"title"),place=places.find(p=>p.id===bundle.placeId);meta.textContent=[activityNames.join(" + "),place?.name].filter(Boolean).join(" · ")||"Inga delar valda";body.append(title,meta);const actions=document.createElement("div");actions.className="collection-actions";const plan=document.createElement("button");plan.className="small-button";plan.textContent="Planera";plan.onclick=()=>openPlanDialog(bundle.name,null,bundle.activityIds?.[0]||"",bundle.id);const edit=document.createElement("button");edit.className="text-button";edit.textContent="Redigera";edit.onclick=()=>openBundleDialog(bundle);actions.append(plan,edit);card.append(icon,body,actions);$("#bundle-list").append(card);});
}

function renderPlaces() {
  const places=read(keys.places);$("#place-list").replaceChildren();$("#place-empty").hidden=places.length>0;
  places.forEach(place=>{const card=document.createElement("article");card.className="collection-card";const icon=document.createElement("span");icon.className="collection-icon place-icon";icon.textContent="⌖";const body=document.createElement("div"),title=document.createElement("h2"),meta=document.createElement("p");title.textContent=place.name;meta.textContent=[place.category,place.address].filter(Boolean).join(" · ");body.append(title,meta);const actions=document.createElement("div");actions.className="collection-actions";const plan=document.createElement("button");plan.className="small-button";plan.textContent="Planera";plan.onclick=()=>openPlanDialog(`Besök ${place.name}`);const edit=document.createElement("button");edit.className="text-button";edit.textContent="Redigera";edit.onclick=()=>openPlaceDialog(place);actions.append(plan,edit);card.append(icon,body,actions);$("#place-list").append(card);});
}

function renderEntity() {
  if(!currentEntity)return;const collection=currentEntity.type==="person"?read(keys.people):currentEntity.type==="circle"?read(keys.circles):read(keys.activities);const item=collection.find(i=>i.id===currentEntity.id);if(!item){$("#entity-dialog").close();return;}
  $("#entity-type").textContent=currentEntity.type==="person"?"Person":currentEntity.type==="circle"?"Cirkel":"Aktivitet";$("#entity-title").textContent=item.name||item.title;$("#entity-subtitle").textContent=currentEntity.type==="person"?[item.group,interestList(item.interests).join(", "),`kontakt var ${item.frequency} dag`].filter(Boolean).join(" · "):currentEntity.type==="circle"?`${(item.personIds||[]).length} personer`:item.category;
  const agendaAvailable=currentEntity.type!=="activity";$("#entity-tabs").hidden=!agendaAvailable;$("#agenda-panel").hidden=!agendaAvailable;$("#history-panel").hidden=agendaAvailable; if(agendaAvailable){$$('#entity-tabs button').forEach(b=>b.classList.toggle("is-active",b.dataset.entityTab==="agenda"));renderAgenda();}
  renderEntityHistory();
}

function openEntity(type,id){currentEntity={type,id};renderEntity();$("#entity-dialog").showModal();}

function renderAgenda(){const items=read(keys.agenda).filter(a=>a.ownerType===currentEntity.type&&a.ownerId===currentEntity.id);const active=$("#agenda-active"),history=$("#agenda-history");active.replaceChildren();history.replaceChildren();items.filter(a=>!a.completedAt).forEach(item=>makeAgendaItem(item,active,false));items.filter(a=>a.completedAt).sort((a,b)=>b.completedAt.localeCompare(a.completedAt)).forEach(item=>makeAgendaItem(item,history,true));if(!active.children.length)active.innerHTML='<p class="field-empty">Agendan är tom.</p>';if(!history.children.length)history.innerHTML='<p class="field-empty">Inget avbockat ännu.</p>';}
function makeAgendaItem(item,target,done){const row=document.createElement("div");row.className=`agenda-item${done?" is-done":""}`;const button=document.createElement("button");button.className="agenda-check";button.textContent=done?"✓":"";button.setAttribute("aria-label",done?"Flytta tillbaka till agendan":"Bocka av");button.onclick=()=>{const all=read(keys.agenda),found=all.find(a=>a.id===item.id);found.completedAt=done?null:new Date().toISOString();write(keys.agenda,all);renderEntity();};const text=document.createElement("span");text.textContent=item.text;row.append(button,text);target.append(row);}

function renderEntityHistory(){const events=read(keys.events).filter(event=>currentEntity.type==="person"?(event.personIds||[]).includes(currentEntity.id):currentEntity.type==="circle"?(event.circleIds||[]).includes(currentEntity.id):event.activityId===currentEntity.id).sort((a,b)=>`${b.date} ${b.time||""}`.localeCompare(`${a.date} ${a.time||""}`));$("#entity-history").replaceChildren();$("#entity-history-empty").hidden=events.length>0;events.forEach(event=>makeEventCard(event,$("#entity-history")));}

function openPlanDialog(title="",plan=null,activityId="",bundleId="") {const f=$("#plan-form");f.reset();fillActivitySelect(f.elements.activityId,plan?.activityId||activityId);checkboxList($("#plan-people"),read(keys.people),"personIds",plan?.personIds||[]);checkboxList($("#plan-circles"),read(keys.circles),"circleIds",plan?.circleIds||[]);f.elements.id.value=plan?.id||"";f.elements.bundleId.value=plan?.bundleId||bundleId;f.elements.title.value=plan?.title||title;f.elements.date.value=plan?.date||selectedDate;f.elements.time.value=plan?.time||"18:00";f.elements.notes.value=plan?.notes||"";$("#plan-dialog-title").textContent=plan?"Redigera plan":"Lägg till en plan";$("#plan-dialog").showModal();}
function openPersonDialog(person=null){const f=$("#person-form");f.reset();f.elements.id.value=person?.id||"";f.elements.name.value=person?.name||"";f.elements.group.value=person?.group||"Vänner";f.elements.interests.value=interestList(person?.interests).join(", ");f.elements.frequency.value=person?.frequency||7;f.elements.notes.value=person?.notes||"";$("#person-dialog-title").textContent=person?person.name:"Ny person";$("#person-dialog").showModal();}
function openCircleDialog(circle=null){const f=$("#circle-form");f.reset();f.elements.id.value=circle?.id||"";f.elements.name.value=circle?.name||"";f.elements.notes.value=circle?.notes||"";checkboxList($("#circle-people"),read(keys.people),"personIds",circle?.personIds||[]);$("#circle-dialog-title").textContent=circle?circle.name:"Ny cirkel";$("#circle-dialog").showModal();}
function openActivityDialog(activity=null){const f=$("#activity-form");f.reset();f.elements.id.value=activity?.id||"";f.elements.title.value=activity?.title||"";f.elements.category.value=activity?.category||"Fika";f.elements.cost.value=activity?.cost??0;f.elements.duration.value=activity?.duration??60;f.elements.activityLevel.value=activity?.activityLevel??0;f.elements.socialLevel.value=activity?.socialLevel??0;f.elements.place.value=activity?.place||"";$("#activity-dialog-title").textContent=activity?"Redigera aktivitet":"Ny idé";$("#activity-dialog").showModal();}
function fillPlaceSelect(select,selected=""){const first=select.querySelector("option[value='']");select.replaceChildren(first||new Option("Ingen vald plats",""));read(keys.places).forEach(place=>select.add(new Option(place.name,place.id)));select.value=selected||"";}
function openBundleDialog(bundle=null){const f=$("#bundle-form");f.reset();f.elements.id.value=bundle?.id||"";f.elements.name.value=bundle?.name||"";f.elements.notes.value=bundle?.notes||"";checkboxList($("#bundle-activities"),read(keys.activities),"activityIds",bundle?.activityIds||[]);fillPlaceSelect(f.elements.placeId,bundle?.placeId||"");$("#bundle-dialog-title").textContent=bundle?"Redigera evenemang":"Nytt evenemang";$("#bundle-dialog").showModal();}
function openPlaceDialog(place=null){const f=$("#place-form");f.reset();f.elements.id.value=place?.id||"";f.elements.name.value=place?.name||"";f.elements.address.value=place?.address||"";f.elements.category.value=place?.category||"Café";f.elements.notes.value=place?.notes||"";$("#place-dialog-title").textContent=place?"Redigera plats":"Ny plats";$("#place-dialog").showModal();}
function openEventDialog(prefill=currentEntity){const f=$("#event-form");f.reset();f.elements.date.value=todayKey;f.elements.time.value="18:00";fillActivitySelect(f.elements.activityId,prefill?.type==="activity"?prefill.id:"");checkboxList($("#event-people"),read(keys.people),"personIds",prefill?.type==="person"?[prefill.id]:[]);checkboxList($("#event-circles"),read(keys.circles),"circleIds",prefill?.type==="circle"?[prefill.id]:[]);$("#event-dialog").showModal();}

function renderAll(){renderToday();renderPeople();renderCalendar();renderActivities();renderBundles();renderPlaces();if($("#entity-dialog").open)renderEntity();}

function setBackupStatus(message,state="neutral"){const status=$("#backup-status");status.textContent=message;status.dataset.state=state;}
function initBackupTools(){const fileInput=$("#import-data-file");$("#export-data").onclick=()=>{const backup={format:"social-circle-backup",exportVersion:1,appVersion:APP_VERSION,exportedAt:new Date().toISOString(),database:store.snapshot()},blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`social-circle-backup-${todayKey}.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setBackupStatus(`Säkerhetskopian social-circle-backup-${todayKey}.json har skapats.`,"success");};$("#import-data").onclick=()=>fileInput.click();fileInput.onchange=async()=>{const file=fileInput.files?.[0];if(!file)return;if(file.size>20*1024*1024){setBackupStatus("Filen är större än 20 MB och importerades inte.","error");fileInput.value="";return;}try{const parsed=JSON.parse(await file.text()),database=parsed?.format==="social-circle-backup"?parsed.database:parsed;if(!confirm("Importen ersätter all nuvarande lokal data. Vill du fortsätta?")){fileInput.value="";return;}store.replace(database);setBackupStatus(`Importerade ${file.name}. All data är nu sparad i localStorage.`,"success");}catch(error){setBackupStatus(`Filen kunde inte importeras: ${error.message}`,"error");}fileInput.value="";};$("#clear-local-data").onclick=()=>{if(!confirm("Vill du tömma all Social Circle-data i den här webbläsaren? Exportera gärna en säkerhetskopia först."))return;try{if(!store.clear())throw new Error("Rensningen kunde inte verifieras");setBackupStatus("All lokal Social Circle-data har tagits bort.","success");alert("Klart! All lokal Social Circle-data har tagits bort.");location.hash="today";}catch(error){setBackupStatus(`Data kunde inte tas bort: ${error.message}`,"error");alert("Data kunde inte tas bort. Försök igen eller kontrollera webbläsarens lagringsinställningar.");}};}

$$('[data-open]').forEach(button=>button.onclick=()=>button.dataset.open==="person-dialog"?openPersonDialog():button.dataset.open==="circle-dialog"?openCircleDialog():button.dataset.open==="bundle-dialog"?openBundleDialog():button.dataset.open==="place-dialog"?openPlaceDialog():openActivityDialog());
$$('[data-add-plan]').forEach(button=>button.onclick=()=>openPlanDialog());$$('[data-close]').forEach(button=>button.onclick=()=>$("#"+button.dataset.close).close());$$('dialog').forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close();}));
$$('[data-go]').forEach(button=>button.onclick=()=>{location.hash=button.dataset.go;});
$("#add-relationship").onclick=()=>relationshipMode==="people"?openPersonDialog():openCircleDialog();
$("#relationship-tabs").onclick=e=>{if(!e.target.dataset.mode)return;relationshipMode=e.target.dataset.mode;$$('#relationship-tabs button').forEach(b=>b.classList.toggle("is-active",b===e.target));$("#people-panel").hidden=relationshipMode!=="people";$("#circles-panel").hidden=relationshipMode!=="circles";$("#add-relationship").setAttribute("aria-label",relationshipMode==="people"?"Lägg till person":"Skapa cirkel");};
$("#entity-tabs").onclick=e=>{if(!e.target.dataset.entityTab)return;$$('#entity-tabs button').forEach(b=>b.classList.toggle("is-active",b===e.target));$("#agenda-panel").hidden=e.target.dataset.entityTab!=="agenda";$("#history-panel").hidden=e.target.dataset.entityTab!=="history";};
$("#edit-entity").onclick=()=>{const type=currentEntity.type,id=currentEntity.id;$("#entity-dialog").close();type==="person"?openPersonDialog(read(keys.people).find(i=>i.id===id)):type==="circle"?openCircleDialog(read(keys.circles).find(i=>i.id===id)):openActivityDialog(read(keys.activities).find(i=>i.id===id));};$("#log-for-entity").onclick=()=>openEventDialog();

$("#agenda-form").onsubmit=e=>{e.preventDefault();const text=new FormData(e.currentTarget).get("text").trim();if(!text)return;const agenda=read(keys.agenda);agenda.push({id:uid(),ownerType:currentEntity.type,ownerId:currentEntity.id,text,createdAt:new Date().toISOString(),completedAt:null});write(keys.agenda,agenda);e.currentTarget.reset();renderEntity();};
$("#plan-form").onsubmit=e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const d=new FormData(e.currentTarget),plans=read(keys.plans),old=plans.find(p=>p.id===d.get("id")),item={id:d.get("id")||uid(),title:d.get("title").trim(),date:d.get("date"),time:d.get("time"),activityId:d.get("activityId"),bundleId:d.get("bundleId"),personIds:d.getAll("personIds"),circleIds:d.getAll("circleIds"),notes:d.get("notes").trim(),status:old?.status||"planned",createdAt:old?.createdAt||new Date().toISOString()},index=plans.findIndex(p=>p.id===item.id);index>=0?plans[index]=item:plans.push(item);if(item.status==="completed"){const events=read(keys.events),linked=events.find(event=>event.sourcePlanId===item.id);if(linked){Object.assign(linked,{title:item.title,date:item.date,time:item.time,activityId:item.activityId,bundleId:item.bundleId,personIds:expandCircleMembers(item.personIds,item.circleIds),circleIds:item.circleIds,notes:item.notes});store.set(keys.events,events);}}write(keys.plans,plans);$("#plan-dialog").close();};
$("#person-form").onsubmit=e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const d=new FormData(e.currentTarget),people=read(keys.people),old=people.find(p=>p.id===d.get("id")),item={id:d.get("id")||uid(),name:d.get("name").trim(),group:d.get("group"),interests:[...new Set(d.get("interests").split(",").map(value=>value.trim()).filter(Boolean))],frequency:Number(d.get("frequency")),notes:d.get("notes").trim(),lastContact:old?.lastContact||null},index=people.findIndex(p=>p.id===item.id);index>=0?people[index]=item:people.push(item);write(keys.people,people);$("#person-dialog").close();};
$("#circle-form").onsubmit=e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const d=new FormData(e.currentTarget),circles=read(keys.circles),item={id:d.get("id")||uid(),name:d.get("name").trim(),personIds:d.getAll("personIds"),notes:d.get("notes").trim()},index=circles.findIndex(c=>c.id===item.id);index>=0?circles[index]=item:circles.push(item);write(keys.circles,circles);$("#circle-dialog").close();};
$("#activity-form").onsubmit=e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const d=new FormData(e.currentTarget),activities=read(keys.activities),old=activities.find(a=>a.id===d.get("id")),item={id:d.get("id")||uid(),title:d.get("title").trim(),category:d.get("category"),cost:Number(d.get("cost")),duration:Number(d.get("duration")),activityLevel:Number(d.get("activityLevel")),socialLevel:Number(d.get("socialLevel")),place:d.get("place").trim()||"Ej angivet",favorite:old?.favorite||false},index=activities.findIndex(a=>a.id===item.id);index>=0?activities[index]=item:activities.push(item);write(keys.activities,activities);$("#activity-dialog").close();};
$("#bundle-form").onsubmit=e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const d=new FormData(e.currentTarget),bundles=read(keys.bundles),old=bundles.find(b=>b.id===d.get("id")),item={id:d.get("id")||uid(),name:d.get("name").trim(),activityIds:d.getAll("activityIds"),placeId:d.get("placeId"),notes:d.get("notes").trim(),createdAt:old?.createdAt||new Date().toISOString()},index=bundles.findIndex(b=>b.id===item.id);index>=0?bundles[index]=item:bundles.push(item);write(keys.bundles,bundles);$("#bundle-dialog").close();};
$("#place-form").onsubmit=e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const d=new FormData(e.currentTarget),places=read(keys.places),item={id:d.get("id")||uid(),name:d.get("name").trim(),address:d.get("address").trim(),category:d.get("category"),notes:d.get("notes").trim()},index=places.findIndex(p=>p.id===item.id);index>=0?places[index]=item:places.push(item);write(keys.places,places);$("#place-dialog").close();};
$("#event-form").onsubmit=e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const d=new FormData(e.currentTarget),circleIds=d.getAll("circleIds"),events=read(keys.events);events.push({id:uid(),title:d.get("title").trim(),date:d.get("date"),time:d.get("time"),activityId:d.get("activityId"),personIds:expandCircleMembers(d.getAll("personIds"),circleIds),circleIds,notes:d.get("notes").trim(),createdAt:new Date().toISOString()});write(keys.events,events);$("#event-dialog").close();renderEntity();};

$("#people-filters").onclick=e=>{if(!e.target.dataset.group)return;peopleFilter=e.target.dataset.group;$$('#people-filters .filter-chip').forEach(b=>b.classList.toggle("is-active",b===e.target));renderPeople();};$("#activity-filters").onclick=e=>{if(!e.target.dataset.activityFilter)return;activityFilter=e.target.dataset.activityFilter;$$('#activity-filters .filter-chip').forEach(b=>b.classList.toggle("is-active",b===e.target));renderActivities();};$("#activity-category-filter").onchange=e=>{activityCategory=e.target.value;renderActivities();};$("#activity-sort").onchange=e=>{activitySort=e.target.value;renderActivities();};
$("#activity-tabs").onclick=e=>{if(!e.target.dataset.contentMode)return;activityContentMode=e.target.dataset.contentMode;$$('#activity-tabs button').forEach(b=>b.classList.toggle("is-active",b===e.target));["activities","bundles","places"].forEach(mode=>$("#"+mode+"-panel").hidden=mode!==activityContentMode);$("#add-activity-content").setAttribute("aria-label",activityContentMode==="activities"?"Lägg till aktivitet":activityContentMode==="bundles"?"Skapa evenemang":"Lägg till plats");};$("#add-activity-content").onclick=()=>activityContentMode==="activities"?openActivityDialog():activityContentMode==="bundles"?openBundleDialog():openPlaceDialog();
$("#calendar-modes").onclick=e=>{if(!e.target.dataset.calendarMode)return;calendarMode=e.target.dataset.calendarMode;shownMonth=calendarMode==="month"?new Date(new Date().getFullYear(),new Date().getMonth(),1):new Date();selectedDate=todayKey;$$('#calendar-modes button').forEach(b=>b.classList.toggle("is-active",b===e.target));renderCalendar();};$("#prev-month").onclick=()=>shiftCalendar(-1);$("#next-month").onclick=()=>shiftCalendar(1);
$("#calendar-agenda-tabs").onclick=e=>{if(!e.target.dataset.agendaMode)return;calendarAgendaMode=e.target.dataset.agendaMode;$$('#calendar-agenda-tabs button').forEach(button=>button.classList.toggle("is-active",button===e.target));renderCalendar();};

const formatted=prettyDate(todayKey);$("#today-date").textContent=formatted.charAt(0).toUpperCase()+formatted.slice(1);store.subscribe(renderAll);window.addEventListener("hashchange",showView);initFileTest();initBackupTools();initVersionInfo();showView();renderAll();
